sudo: required
services:
    docker

before-install:
    - docker build -t emailzunk/docker-react-dev -f Dockerfile.dev .

script:
    - docker run emailzunk/docker-react-dev npm run test -- -- coverage