sudo: required
language: generic
services:
    docker

before-install:
    - docker build -t emailzunk/docker-react-dev -f Dockerfile.dev .

script:
    - docker run -e CI=true emailzunk/docker-react-dev npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react-dev"
    env: "DockerReactDev-env"
    bucket_name: "elasticbeanstalk-eu-west-1-810639626792"
    bucket_path: "docker-react-dev"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY